#!/usr/bin/env node

/*
MyAPI distribution and self-hosting tooling.
Copyright (C) 2026 ForceMind

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/
import { randomBytes } from 'node:crypto'
import {
  chmodSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { spawnSync } from 'node:child_process'
import { homedir, platform } from 'node:os'
import { isIP } from 'node:net'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const packageMetadata = JSON.parse(
  readFileSync(path.join(packageRoot, 'package.json'), 'utf8')
)

// Deployment variables use the MYAPI_* prefix for new installations. The
// legacy NEW_API_* names are intentionally read-only aliases: existing .env
// files continue to work, while every file generated by this CLI uses the
// canonical names. These aliases cover only distribution-level settings; the
// application's SQL/JWT/Redis environment and on-disk contracts are left
// untouched for safe data adoption.
const deploymentEnvAliases = Object.freeze({
  MYAPI_IMAGE: 'NEW_API_IMAGE',
  MYAPI_PORT: 'NEW_API_PORT',
  MYAPI_PUBLIC_URL: 'NEW_API_PUBLIC_URL',
  MYAPI_DATA_DIR: 'NEW_API_DATA_DIR',
  MYAPI_LOGS_DIR: 'NEW_API_LOGS_DIR',
})

const deploymentDefaults = Object.freeze({
  MYAPI_IMAGE: `ghcr.io/forcemind/myapi:v${packageMetadata.version}`,
  MYAPI_EDITION: 'full',
  MYAPI_PORT: '3000',
  MYAPI_BIND_ADDRESS: '127.0.0.1',
  // Conservative defaults keep Docker Desktop/LAN Lite from saturating a
  // workstation. Operators can raise these after measuring their workload.
  MYAPI_CPU_LIMIT: '2.0',
  MYAPI_MEMORY_LIMIT: '2g',
  MYAPI_PUBLIC_URL: 'https://my-api.example.com',
  MYAPI_DATA_DIR: './data',
  MYAPI_LOGS_DIR: './logs',
})

const excludedSourceParts = new Set([
  '.git',
  '.github',
  '.codex',
  '.agents',
  'node_modules',
  'dist',
  'coverage',
])

function fail(message) {
  console.error(`MyAPI: ${message}`)
  process.exitCode = 1
}

function argumentValue(args, name) {
  const index = args.indexOf(name)
  if (index === -1 || index === args.length - 1) return undefined
  return args[index + 1]
}

function validateArguments(
  args,
  { values = [], flags = [], positional = 0 } = {}
) {
  const valueOptions = new Set(values)
  const flagOptions = new Set(flags)
  let positionalCount = 0
  for (let index = 0; index < args.length; index++) {
    const argument = args[index]
    if (!argument.startsWith('-')) {
      positionalCount += 1
      continue
    }
    if (flagOptions.has(argument)) continue
    if (!valueOptions.has(argument)) {
      throw new Error(`unknown option ${argument}`)
    }
    const value = args[index + 1]
    if (!value || value.startsWith('-')) {
      throw new Error(`${argument} requires a value`)
    }
    index += 1
  }
  if (positionalCount > positional) {
    throw new Error('too many positional arguments')
  }
}

function validatePublicOrigin(value) {
  try {
    const url = new URL(value)
    const hostname = url.hostname.toLowerCase()
    return (
      url.protocol === 'https:' &&
      !url.username &&
      !url.password &&
      url.pathname === '/' &&
      !url.search &&
      !url.hash &&
      hostname !== 'localhost' &&
      !hostname.endsWith('.localhost') &&
      hostname !== 'example.com' &&
      !hostname.endsWith('.example.com')
    )
  } catch {
    return false
  }
}

function deploymentValue(values, canonicalKey) {
  const canonicalValue = values[canonicalKey]
  if (canonicalValue !== undefined && canonicalValue !== '') {
    return canonicalValue
  }
  const legacyKey = deploymentEnvAliases[canonicalKey]
  if (legacyKey) {
    const legacyValue = values[legacyKey]
    if (legacyValue !== undefined && legacyValue !== '') return legacyValue
  }
  return undefined
}

function legacyDeploymentKeys(values) {
  return Object.entries(deploymentEnvAliases)
    .filter(([, legacyKey]) => {
      const legacyValue = values[legacyKey]
      return legacyValue !== undefined && legacyValue !== ''
    })
    .map(([, legacyKey]) => legacyKey)
}

function warnLegacyDeploymentKeys(values) {
  const legacyKeys = legacyDeploymentKeys(values)
  if (legacyKeys.length === 0) return
  console.error(
    `MyAPI: compatibility fallback for ${legacyKeys.join(', ')}; ` +
      'run "myapi migrate --project-dir DIR" to write MYAPI_* settings.'
  )
}

function composeEnvironment(values) {
  const environment = { ...process.env }
  for (const canonicalKey of Object.keys(deploymentEnvAliases)) {
    const value = deploymentValue(values, canonicalKey)
    if (value !== undefined) environment[canonicalKey] = value
  }
  for (const key of [
    'MYAPI_EDITION',
    'MYAPI_BIND_ADDRESS',
    'MYAPI_ALLOW_LAN',
    'MYAPI_SESSION_COOKIE_SECURE',
    'MYAPI_CPU_LIMIT',
    'MYAPI_MEMORY_LIMIT',
    'MYAPI_BUILD_PARALLELISM',
  ]) {
    if (values[key] !== undefined && values[key] !== '') environment[key] = values[key]
  }
  return environment
}

function deploymentImage(values) {
  return deploymentValue(values, 'MYAPI_IMAGE') || deploymentDefaults.MYAPI_IMAGE
}

function shouldBuildLocalImage(values) {
  return values.MYAPI_BUILD_LOCAL === 'true' || deploymentImage(values).startsWith('local/')
}

function validateRuntimeConfiguration(values) {
  const errors = []
  const edition = values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION
  if (!['full', 'lan'].includes(edition)) {
    errors.push('MYAPI_EDITION must be full or lan')
  }
  const publicUrl = deploymentValue(values, 'MYAPI_PUBLIC_URL') || ''
  const lanPlaceholder =
    edition === 'lan' &&
    (publicUrl === '' ||
      publicUrl === 'https://my-api.example.com' ||
      publicUrl === 'https://new-api.example.com')
  const lanOrigin = edition === 'lan' && validateLanOrigin(publicUrl)
  if (!lanPlaceholder && !lanOrigin && !validatePublicOrigin(publicUrl)) {
    errors.push(
      edition === 'lan'
        ? 'MYAPI_PUBLIC_URL must be a localhost or private-network origin in LAN edition'
        : 'MYAPI_PUBLIC_URL must be an exact non-placeholder HTTPS origin'
    )
  }
  const sessionSecret = values.SESSION_SECRET || ''
  if (sessionSecret.length < 48 || sessionSecret.includes('replace-with')) {
    errors.push('SESSION_SECRET must be a generated secret of at least 48 characters')
  }
  const port = Number(
    deploymentValue(values, 'MYAPI_PORT') || deploymentDefaults.MYAPI_PORT
  )
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    errors.push('MYAPI_PORT must be an integer between 1 and 65535')
  }
  const bindAddress = values.MYAPI_BIND_ADDRESS || deploymentDefaults.MYAPI_BIND_ADDRESS
  if (!validateBindAddress(bindAddress)) {
    errors.push('MYAPI_BIND_ADDRESS must be a valid host address')
  }
  const allowLAN = values.MYAPI_ALLOW_LAN || 'false'
  if (!['true', 'false'].includes(allowLAN)) {
    errors.push('MYAPI_ALLOW_LAN must be true or false')
  } else {
    const bindingError = validateLANBinding(bindAddress, allowLAN === 'true')
    if (bindingError) errors.push(bindingError)
  }
  const cpuLimit = values.MYAPI_CPU_LIMIT || deploymentDefaults.MYAPI_CPU_LIMIT
  if (!/^\d+(?:\.\d+)?$/.test(String(cpuLimit)) || Number(cpuLimit) <= 0 || Number(cpuLimit) > 64) {
    errors.push('MYAPI_CPU_LIMIT must be a number greater than 0 and no more than 64')
  }
  const memoryLimit = values.MYAPI_MEMORY_LIMIT || deploymentDefaults.MYAPI_MEMORY_LIMIT
  if (!/^\d+(?:\.\d+)?(?:b|k|kb|m|mb|g|gb|t|tb)$/i.test(String(memoryLimit)) || Number.parseFloat(memoryLimit) <= 0) {
    errors.push('MYAPI_MEMORY_LIMIT must be a positive Docker size such as 512m or 2g')
  }
  const buildParallelism = values.MYAPI_BUILD_PARALLELISM || '2'
  if (!/^[1-9]\d*$/.test(String(buildParallelism)) || Number(buildParallelism) > 64) {
    errors.push('MYAPI_BUILD_PARALLELISM must be a positive integer no more than 64')
  }
  return errors
}

function normalizeLANRuntimeValues(values) {
  if ((values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION) !== 'lan') return
  const publicUrl = deploymentValue(values, 'MYAPI_PUBLIC_URL') || ''
  if (
    publicUrl === '' ||
    publicUrl === 'https://my-api.example.com' ||
    publicUrl === 'https://new-api.example.com'
  ) {
    const port = deploymentValue(values, 'MYAPI_PORT') || deploymentDefaults.MYAPI_PORT
    values.MYAPI_PUBLIC_URL = `http://localhost:${port}`
  }
  if (values.MYAPI_PUBLIC_URL.startsWith('http://') && values.MYAPI_SESSION_COOKIE_SECURE === 'true') {
    values.MYAPI_SESSION_COOKIE_SECURE = 'false'
  }
}

function validateLanOrigin(value) {
  try {
    const url = new URL(value)
    if (!['http:', 'https:'].includes(url.protocol)) return false
    if (url.username || url.password || url.pathname !== '/' || url.search || url.hash) {
      return false
    }
    const hostname = url.hostname.toLowerCase()
    return (
      hostname === 'localhost' ||
      isLoopbackIPv4(hostname) ||
      hostname === '::1' || hostname === '[::1]' ||
      isPrivateIPv4(hostname)
    )
  } catch {
    return false
  }
}

function validateBindAddress(value) {
  const address = String(value || '').trim().toLowerCase()
  return address === 'localhost' || address === '0.0.0.0' ||
    isLoopbackIPv4(address) || isPrivateIPv4(address)
}

function isLoopbackIPv4(value) {
  return isIP(value) === 4 && value === '127.0.0.1'
}

function isPrivateIPv4(value) {
  if (isIP(value) !== 4) return false
  const octets = value.split('.').map(Number)
  if (octets.length !== 4 || octets.some((octet) => !Number.isInteger(octet) || octet < 0 || octet > 255)) return false
  return octets[0] === 10 ||
    (octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31) ||
    (octets[0] === 192 && octets[1] === 168)
}

function isLoopbackBindAddress(value) {
  const address = String(value || '').trim().toLowerCase()
  return address === 'localhost' || address === '127.0.0.1' || address === '::1' || address === '[::1]'
}

function isPrivateBindAddress(value) {
  const address = String(value || '').trim().toLowerCase()
  return address === '0.0.0.0' || isPrivateIPv4(address)
}

function validateLANBinding(value, allowLAN = false) {
  if (!validateBindAddress(value)) return 'MYAPI_BIND_ADDRESS must be localhost, loopback, 0.0.0.0, or a private IPv4 address'
  if (!isLoopbackBindAddress(value) && !allowLAN) {
    return 'LAN binding is disabled by default; pass --allow-lan to share on a private network'
  }
  if (!isLoopbackBindAddress(value) && !isPrivateBindAddress(value)) {
    return 'LAN binding must use a private IPv4 address or 0.0.0.0'
  }
  return undefined
}

function defaultLANProjectDirectory() {
  // Keep the default predictable and local. The data directory remains inside
  // the project rather than reading any platform credential directory.
  return path.resolve('myapi-lan')
}

function defaultLANDataHint() {
  if (platform() === 'win32') return path.join(homedir(), 'AppData', 'Local', 'MyAPI', 'lan')
  if (platform() === 'darwin') return path.join(homedir(), 'Library', 'Application Support', 'MyAPI', 'lan')
  return path.join(homedir(), '.local', 'share', 'myapi', 'lan')
}

function projectRootFromArgs(args) {
  const explicit = argumentValue(args, '--project-dir')
  return path.resolve(explicit || process.cwd())
}

function parseEnvFileContents(contents) {
  const values = {}
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const separator = line.indexOf('=')
    if (separator <= 0) continue
    const key = line.slice(0, separator).trim()
    if (!/^[A-Z][A-Z0-9_]*$/.test(key)) continue
    values[key] = line.slice(separator + 1).trim()
  }
  return values
}

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return {}
  return parseEnvFileContents(readFileSync(filePath, 'utf8'))
}

function setEnvValue(contents, key, value) {
  const safeValue = String(value).replace(/[\r\n]/g, '')
  const line = `${key}=${safeValue}`
  const pattern = new RegExp(`^${key}=.*$`, 'm')
  if (pattern.test(contents)) return contents.replace(pattern, line)
  return `${contents.trimEnd()}\n${line}\n`
}

function commentLegacyEnvValue(contents, legacyKey, canonicalKey) {
  const pattern = new RegExp(`^(\\s*)${legacyKey}=([^\\r\\n]*)$`, 'gm')
  return contents.replace(
    pattern,
    (_match, indentation, value) =>
      `${indentation}# Legacy ${legacyKey} migrated to ${canonicalKey}: ${legacyKey}=${value}`
  )
}

function migrateDeploymentEnv(args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi configure" before migrating deployment settings')
  }

  let contents = readFileSync(paths.envFile, 'utf8')
  let values = parseEnvFile(paths.envFile)
  const migrated = []
  const conflicts = []

  for (const [canonicalKey, legacyKey] of Object.entries(deploymentEnvAliases)) {
    const legacyValue = values[legacyKey]
    if (legacyValue === undefined || legacyValue === '') continue
    const canonicalValue = values[canonicalKey]
    if (canonicalValue !== undefined && canonicalValue !== '') {
      conflicts.push(`${canonicalKey}/${legacyKey}`)
      continue
    }
    contents = setEnvValue(contents, canonicalKey, legacyValue)
    contents = commentLegacyEnvValue(contents, legacyKey, canonicalKey)
    migrated.push(`${legacyKey} -> ${canonicalKey}`)
    values = parseEnvFileContents(contents)
  }

  if (migrated.length > 0) {
    writeFileSync(paths.envFile, contents, { mode: 0o600 })
    chmodSync(paths.envFile, 0o600)
    console.log(`Migrated deployment settings in ${paths.envFile}:`)
    for (const item of migrated) console.log(`  ${item}`)
  } else {
    console.log(`No legacy NEW_API_* settings needed migration in ${paths.envFile}.`)
  }
  if (conflicts.length > 0) {
    console.error(
      `MYAPI_* values already take precedence over legacy settings: ${conflicts.join(', ')}`
    )
  }
}

function deploymentPaths(projectRoot) {
  const deployDir = path.join(projectRoot, 'deploy')
  return {
    projectRoot,
    deployDir,
    composeFile: path.join(deployDir, 'docker-compose.yml'),
    envFile: path.join(deployDir, '.env'),
    envExample: path.join(deployDir, '.env.example'),
  }
}

function assertDeploymentSource(paths) {
  if (!existsSync(paths.composeFile) || !existsSync(paths.envExample)) {
    throw new Error(
      `deployment files were not found under ${paths.deployDir}; run "myapi init" first`
    )
  }
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    encoding: 'utf8',
    env: options.env,
    stdio: options.capture ? 'pipe' : 'inherit',
    shell: false,
  })
  if (options.capture) return result
  if (result.error) throw result.error
  if (result.status !== 0) {
    throw new Error(`${command} exited with status ${result.status ?? 'unknown'}`)
  }
  return result
}

function composeArguments(paths, args) {
  return [
    'compose',
    '--env-file',
    paths.envFile,
    '-f',
    paths.composeFile,
    ...args,
  ]
}

function shouldCopySource(sourcePath) {
  const relative = path.relative(packageRoot, sourcePath)
  if (!relative) return true
  const parts = relative.split(path.sep)
  if (parts.some((part) => excludedSourceParts.has(part))) return false
  const portableRelative = parts.join('/')
  if (
    /^(?:data|logs|backups|cache)(?:\/|$)/.test(portableRelative) ||
    /^deploy\/(?:data|logs|backups|cache)(?:\/|$)/.test(portableRelative)
  ) {
    return false
  }
  const basename = parts.at(-1) || ''
  if (basename === '.env' || basename.startsWith('.env.')) {
    return basename === '.env.example'
  }
  if (basename === 'my-api' || basename === 'new-api' || basename === 'one-api') {
    return false
  }
  return !/\.(?:db(?:-.*)?|sqlite3?|log|tgz)$/i.test(basename)
}

function initProject(args, showNextStep = true) {
  const positional = args.find((arg) => !arg.startsWith('-'))
  const destination = path.resolve(positional || 'myapi-source')
  if (existsSync(destination) && readdirSync(destination).length > 0) {
    throw new Error(`refusing to overwrite non-empty directory ${destination}`)
  }

  const staging = `${destination}.myapi-init-${process.pid}`
  if (existsSync(staging)) rmSync(staging, { recursive: true, force: true })
  mkdirSync(path.dirname(destination), { recursive: true })
  cpSync(packageRoot, staging, {
    recursive: true,
    filter: shouldCopySource,
  })
  // An initialized deployment is an application workspace, not a package
  // publishing checkout. Mark it private so a later `npm publish` cannot leak
  // a generated deploy/.env or any other local runtime material.
  const initializedPackagePath = path.join(staging, 'package.json')
  const initializedPackage = JSON.parse(
    readFileSync(initializedPackagePath, 'utf8')
  )
  initializedPackage.private = true
  delete initializedPackage.publishConfig
  writeFileSync(
    initializedPackagePath,
    `${JSON.stringify(initializedPackage, null, 2)}\n`
  )
  writeFileSync(
    path.join(staging, '.gitignore'),
    readFileSync(path.join(packageRoot, 'cli/templates/gitignore'), 'utf8')
  )
  writeFileSync(
    path.join(staging, '.npmignore'),
    readFileSync(path.join(packageRoot, 'cli/templates/npmignore'), 'utf8')
  )
  if (existsSync(destination)) rmSync(destination, { recursive: true })
  renameSync(staging, destination)
  console.log(`MyAPI source initialized at ${destination}`)
  if (showNextStep) console.log(`Next: myapi configure --project-dir ${destination}`)
}

function configureProject(args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  assertDeploymentSource(paths)
  if (existsSync(paths.envFile) && !args.includes('--force')) {
    throw new Error(`${paths.envFile} already exists; use --force to replace it`)
  }

  let contents = readFileSync(paths.envExample, 'utf8')
  const publicUrl = argumentValue(args, '--public-url')
  contents = setEnvValue(contents, 'SESSION_SECRET', randomBytes(32).toString('hex'))
  if (publicUrl) contents = setEnvValue(contents, 'MYAPI_PUBLIC_URL', publicUrl)

  const dataDir = argumentValue(args, '--data-dir')
  const logsDir = argumentValue(args, '--logs-dir')
  if (dataDir) contents = setEnvValue(contents, 'MYAPI_DATA_DIR', path.resolve(dataDir))
  if (logsDir) contents = setEnvValue(contents, 'MYAPI_LOGS_DIR', path.resolve(logsDir))

  writeFileSync(paths.envFile, contents, { mode: 0o600 })
  chmodSync(paths.envFile, 0o600)
  const values = parseEnvFile(paths.envFile)
  mkdirSync(
    path.resolve(
      paths.deployDir,
      deploymentValue(values, 'MYAPI_DATA_DIR') || deploymentDefaults.MYAPI_DATA_DIR
    ),
    { recursive: true }
  )
  mkdirSync(
    path.resolve(
      paths.deployDir,
      deploymentValue(values, 'MYAPI_LOGS_DIR') || deploymentDefaults.MYAPI_LOGS_DIR
    ),
    { recursive: true }
  )

  console.log(`Created ${paths.envFile} with mode 0600.`)
  if (!publicUrl) {
    console.log('Set MYAPI_PUBLIC_URL in that file before running myapi up.')
  }
}

function lanImageForVersion() {
  return `ghcr.io/forcemind/myapi-lan:v${packageMetadata.version}`
}

function lanProjectDirectory(args) {
  const explicit = argumentValue(args, '--project-dir')
  let positional
  const valueOptions = new Set(['--project-dir', '--bind-address', '--port'])
  for (let index = 0; index < args.length; index++) {
    const argument = args[index]
    if (valueOptions.has(argument)) {
      index += 1
      continue
    }
    if (!argument.startsWith('-')) {
      positional = argument
      break
    }
  }
  return path.resolve(explicit || positional || defaultLANProjectDirectory())
}

function lanOptions(args) {
  const bindAddress = argumentValue(args, '--bind-address') || deploymentDefaults.MYAPI_BIND_ADDRESS
  const portValue = argumentValue(args, '--port') || deploymentDefaults.MYAPI_PORT
  const port = Number(portValue)
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('--port must be an integer between 1 and 65535')
  }
  const bindingError = validateLANBinding(bindAddress, args.includes('--allow-lan'))
  if (bindingError) throw new Error(bindingError)
  return { bindAddress, port }
}

function writeLANEnvironment(projectRoot, options) {
  const paths = deploymentPaths(projectRoot)
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi lan init" or "myapi configure" before LAN commands')
  }
  let contents = readFileSync(paths.envFile, 'utf8')
  contents = setEnvValue(contents, 'MYAPI_EDITION', 'lan')
  contents = setEnvValue(contents, 'MYAPI_IMAGE', lanImageForVersion())
  contents = setEnvValue(contents, 'MYAPI_BIND_ADDRESS', options.bindAddress)
  contents = setEnvValue(contents, 'MYAPI_ALLOW_LAN', isLoopbackBindAddress(options.bindAddress) ? 'false' : 'true')
  contents = setEnvValue(contents, 'MYAPI_PORT', options.port)
  contents = setEnvValue(contents, 'MYAPI_SESSION_COOKIE_SECURE', 'false')
  const publicHost = isLoopbackBindAddress(options.bindAddress) ? 'localhost' : options.bindAddress
  contents = setEnvValue(contents, 'MYAPI_PUBLIC_URL', `http://${publicHost}:${options.port}`)
  writeFileSync(paths.envFile, contents, { mode: 0o600 })
  chmodSync(paths.envFile, 0o600)
  return paths
}

function printLANEndpoint(values) {
  const bindAddress = values.MYAPI_BIND_ADDRESS || deploymentDefaults.MYAPI_BIND_ADDRESS
  const port = deploymentValue(values, 'MYAPI_PORT') || deploymentDefaults.MYAPI_PORT
  const loopback = isLoopbackBindAddress(bindAddress)
  const displayHost = bindAddress === '0.0.0.0' ? '<private-LAN-IP>' : bindAddress
  console.log(`MyAPI LAN endpoint: http://${displayHost}:${port}`)
  console.log(loopback
    ? 'Loopback-only mode; use --allow-lan with a private bind address to share with colleagues.'
    : 'Private-network mode; create one downstream API Key per colleague in the MyAPI admin UI.')
  console.log('Upstream credentials stay in MyAPI; this command never reads local credential files.')
}

function lanInit(args) {
  const options = lanOptions(args)
  const destination = lanProjectDirectory(args)
  if (existsSync(destination) && readdirSync(destination).length > 0) {
    throw new Error(`refusing to overwrite non-empty directory ${destination}`)
  }
  initProject([destination], false)
  configureProject([
    '--project-dir',
    destination,
    '--public-url',
    `http://${isLoopbackBindAddress(options.bindAddress) ? 'localhost' : options.bindAddress}:${options.port}`,
  ])
  const paths = writeLANEnvironment(destination, options)
  console.log(`LAN edition configured at ${paths.envFile}.`)
  console.log(`Data hint for ${platform()}: ${defaultLANDataHint()}`)
  printLANEndpoint(parseEnvFile(paths.envFile))
}

function lanCommand(command, args) {
  const projectRoot = lanProjectDirectory(args)
  if (command === 'init') {
    lanInit(args)
    return
  }
  const paths = deploymentPaths(projectRoot)
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi lan init" or "myapi configure" before LAN commands')
  }
  const values = parseEnvFile(paths.envFile)
  if ((values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION) !== 'lan') {
    throw new Error(`${paths.envFile} is not configured for MYAPI_EDITION=lan`)
  }
  const configuredBind = values.MYAPI_BIND_ADDRESS || deploymentDefaults.MYAPI_BIND_ADDRESS
  const configuredPort = Number(deploymentValue(values, 'MYAPI_PORT') || deploymentDefaults.MYAPI_PORT)
  const options = {
    bindAddress: argumentValue(args, '--bind-address') || configuredBind,
    port: argumentValue(args, '--port') ? Number(argumentValue(args, '--port')) : configuredPort,
  }
  if (!Number.isInteger(options.port) || options.port < 1 || options.port > 65535) {
    throw new Error('--port must be an integer between 1 and 65535')
  }
  const configuredError = validateLANBinding(
    options.bindAddress,
    args.includes('--allow-lan') || command !== 'start'
  )
  if (configuredError) throw new Error(configuredError)
  if (args.includes('--bind-address') || args.includes('--port')) {
    writeLANEnvironment(projectRoot, options)
    Object.assign(values, parseEnvFile(paths.envFile))
  }
  printLANEndpoint(values)
  if (command === 'start') deploymentCommand('up', args)
  else if (command === 'stop') deploymentCommand('down', args)
  else if (command === 'status') deploymentCommand('status', args)
  else throw new Error(`unknown LAN command "${command}"`)
}

function adoptDataPaths(args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi configure" before adopting data paths')
  }
  const dataDir = argumentValue(args, '--data-dir')
  const logsDir = argumentValue(args, '--logs-dir')
  if (!dataDir || !logsDir) {
    throw new Error('adopt requires both --data-dir and --logs-dir')
  }
  const resolvedDataDir = path.resolve(dataDir)
  const resolvedLogsDir = path.resolve(logsDir)
  for (const target of [resolvedDataDir, resolvedLogsDir]) {
    if (!existsSync(target) || !statSync(target).isDirectory()) {
      throw new Error(`adopt target is not an existing directory: ${target}`)
    }
  }

  let contents = readFileSync(paths.envFile, 'utf8')
  contents = setEnvValue(contents, 'MYAPI_DATA_DIR', resolvedDataDir)
  contents = setEnvValue(contents, 'MYAPI_LOGS_DIR', resolvedLogsDir)
  writeFileSync(paths.envFile, contents, { mode: 0o600 })
  chmodSync(paths.envFile, 0o600)
  warnLegacyDeploymentKeys(parseEnvFile(paths.envFile))
  console.log('Updated deployment data and log paths without moving any files.')
}

function doctor(args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  const checks = []
  const record = (name, ok, detail) => checks.push({ name, ok, detail })

  record('Node.js >= 20', Number(process.versions.node.split('.')[0]) >= 20, process.version)
  const docker = run('docker', ['version', '--format', '{{.Server.Version}}'], {
    capture: true,
  })
  record('Docker daemon', docker.status === 0, docker.status === 0 ? docker.stdout.trim() : 'unavailable')
  const compose = run('docker', ['compose', 'version', '--short'], {
    capture: true,
  })
  record('Docker Compose', compose.status === 0, compose.status === 0 ? compose.stdout.trim() : 'unavailable')
  record('Compose template', existsSync(paths.composeFile), paths.composeFile)
  record('Environment file', existsSync(paths.envFile), paths.envFile)

  const values = parseEnvFile(paths.envFile)
  normalizeLANRuntimeValues(values)
  warnLegacyDeploymentKeys(values)
  const publicUrl = deploymentValue(values, 'MYAPI_PUBLIC_URL') || ''
  const edition = values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION
  const bindAddress = values.MYAPI_BIND_ADDRESS || deploymentDefaults.MYAPI_BIND_ADDRESS
  const allowLAN = values.MYAPI_ALLOW_LAN || 'false'
  const bindingError = validateLANBinding(bindAddress, allowLAN === 'true')
  record(
    'LAN binding',
    ['true', 'false'].includes(allowLAN) && !bindingError,
    bindingError || `bind=${bindAddress}, allow-lan=${allowLAN}`
  )
  record(
    edition === 'lan' ? 'LAN origin' : 'Public HTTPS URL',
    edition === 'lan' ? validateLanOrigin(publicUrl) : validatePublicOrigin(publicUrl),
    publicUrl ? 'configured' : 'missing'
  )
  const sessionSecret = values.SESSION_SECRET || ''
  record(
    'Session secret',
    sessionSecret.length >= 48 && !sessionSecret.includes('replace-with'),
    sessionSecret ? 'configured' : 'missing'
  )
  const composeConfig = existsSync(paths.envFile)
      ? run(
        'docker',
        composeArguments(paths, ['config', '--quiet']),
        {
          cwd: paths.projectRoot,
          capture: true,
          env: composeEnvironment(values),
        }
      )
    : { status: 1, stderr: 'environment file is missing' }
  record(
    'Docker Compose configuration',
    composeConfig.status === 0,
    composeConfig.status === 0
      ? 'valid'
      : (composeConfig.stderr || 'invalid').trim()
  )

  for (const check of checks) {
    console.log(`${check.ok ? 'OK' : 'FAIL'}  ${check.name}: ${check.detail}`)
  }
  if (checks.some((check) => !check.ok)) process.exitCode = 1
}

function deploymentCommand(command, args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi configure" before Docker commands')
  }
  const values = parseEnvFile(paths.envFile)
  normalizeLANRuntimeValues(values)
  warnLegacyDeploymentKeys(values)

  if (command === 'build') {
    const cpuLimit = values.MYAPI_CPU_LIMIT || deploymentDefaults.MYAPI_CPU_LIMIT
    const memoryLimit = values.MYAPI_MEMORY_LIMIT || deploymentDefaults.MYAPI_MEMORY_LIMIT
    if (!/^\d+(?:\.\d+)?$/.test(String(cpuLimit)) || Number(cpuLimit) <= 0 || Number(cpuLimit) > 64) {
      throw new Error('MYAPI_CPU_LIMIT must be a number greater than 0 and no more than 64')
    }
    if (!/^\d+(?:\.\d+)?(?:b|k|kb|m|mb|g|gb|t|tb)$/i.test(String(memoryLimit)) || Number.parseFloat(memoryLimit) <= 0) {
      throw new Error('MYAPI_MEMORY_LIMIT must be a positive Docker size such as 512m or 2g')
    }
    const cpuQuota = String(Math.round(Number(cpuLimit) * 100000))
    run(
      'docker',
      [
        'build',
        '--cpu-period',
        '100000',
        '--cpu-quota',
        cpuQuota,
        '--memory',
        String(memoryLimit),
        '--memory-swap',
        String(memoryLimit),
        '--build-arg',
        `MYAPI_BRAND_NAME=${values.MYAPI_BRAND_NAME || 'MyAPI'}`,
        '--build-arg',
        `MYAPI_BRAND_LOGO=${values.MYAPI_BRAND_LOGO || '/myapi-logo-v1.png'}`,
        '--build-arg',
        `MYAPI_EDITION=${values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION}`,
        '--build-arg',
        `MYAPI_BUILD_PARALLELISM=${values.MYAPI_BUILD_PARALLELISM || '2'}`,
        '-t',
        deploymentImage(values),
        '.',
      ],
      { cwd: paths.projectRoot }
    )
    return
  }

  if (command === 'up') {
    const errors = validateRuntimeConfiguration(values)
    if (errors.length > 0) {
      throw new Error(`deployment preflight failed: ${errors.join('; ')}`)
    }
    const composeConfig = run(
      'docker',
      composeArguments(paths, ['config', '--quiet']),
      {
        cwd: paths.projectRoot,
        capture: true,
        env: composeEnvironment(values),
      }
    )
    if (composeConfig.status !== 0) {
      throw new Error(
        `Docker Compose configuration is invalid: ${(composeConfig.stderr || '').trim()}`
      )
    }
    if (!shouldBuildLocalImage(values)) {
      run('docker', composeArguments(paths, ['pull', 'my-api']), {
        cwd: paths.projectRoot,
        env: composeEnvironment(values),
      })
    }
  }

  let composeCommand
  if (command === 'up') {
    composeCommand = ['up', '-d', '--force-recreate', '--wait', '--wait-timeout', '120']
  }
  else if (command === 'down') composeCommand = ['down']
  else if (command === 'status') composeCommand = ['ps']
  else composeCommand = ['logs', '--tail', '100', ...(args.includes('--follow') ? ['--follow'] : [])]
  run('docker', composeArguments(paths, composeCommand), {
    cwd: paths.projectRoot,
    env: composeEnvironment(values),
  })
}

function imageRepositoryForEdition(edition) {
  return edition === 'lan'
    ? 'ghcr.io/forcemind/myapi-lan'
    : 'ghcr.io/forcemind/myapi'
}

function normalizeReleaseVersion(value) {
  const version = String(value || '').trim()
  const tag = version.startsWith('v') ? version : `v${version}`
  if (!/^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(tag)) {
    throw new Error('--version must be a semantic version such as v0.2.0')
  }
  return tag
}

function shouldVerifyImageSignature(args, values) {
  return args.includes('--verify-signature') || values.MYAPI_VERIFY_IMAGE_SIGNATURE === 'true'
}

function shouldPinImageDigest(args, values) {
  return args.includes('--pin-digest') || values.MYAPI_PIN_IMAGE_DIGEST === 'true'
}

function verifyImageSignature(image, values) {
  const identity = values.MYAPI_COSIGN_CERTIFICATE_IDENTITY || ''
  const issuer = values.MYAPI_COSIGN_CERTIFICATE_OIDC_ISSUER || 'https://token.actions.githubusercontent.com'
  if (!identity) {
    throw new Error(
      'signature verification requires MYAPI_COSIGN_CERTIFICATE_IDENTITY in deploy/.env'
    )
  }
  let result
  try {
    result = run(
      'cosign',
      [
        'verify',
        '--certificate-identity',
        identity,
        '--certificate-oidc-issuer',
        issuer,
        image,
      ],
      { cwd: packageRoot, capture: true }
    )
  } catch (error) {
    throw new Error(`signature verification could not run cosign: ${error.message}`)
  }
  if (result.error) {
    throw new Error(`signature verification could not run cosign: ${result.error.message}`)
  }
  if (result.status !== 0) {
    throw new Error('signature verification failed; deployment was not changed')
  }
}

function resolveImageDigest(image) {
  const repository = image.replace(/:[^/:]+$/, '')
  const result = run(
    'docker',
    ['image', 'inspect', '--format', '{{json .RepoDigests}}', image],
    { cwd: packageRoot, capture: true },
  )
  if (result.error || result.status !== 0) {
    throw new Error('unable to resolve the pulled image digest')
  }
  let references
  try {
    references = JSON.parse(String(result.stdout || '').trim())
  } catch {
    throw new Error('Docker returned an invalid image digest list')
  }
  if (!Array.isArray(references)) {
    throw new Error('Docker returned an invalid image digest list')
  }
  const digestPattern = new RegExp(`^${repository.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}@sha256:[a-f0-9]{64}$`)
  const digest = references.find((reference) => digestPattern.test(String(reference)))
  if (!digest) throw new Error('pulled image did not expose a valid repository digest')
  return digest
}

function buildUpgradePlan(args) {
  const paths = deploymentPaths(projectRootFromArgs(args))
  assertDeploymentSource(paths)
  if (!existsSync(paths.envFile)) {
    throw new Error('run "myapi configure" before upgrading')
  }
  const version = normalizeReleaseVersion(argumentValue(args, '--version'))
  const originalContents = readFileSync(paths.envFile, 'utf8')
  const values = parseEnvFileContents(originalContents)
  const edition = values.MYAPI_EDITION || deploymentDefaults.MYAPI_EDITION
  if (!['full', 'lan'].includes(edition)) {
    throw new Error('upgrade preflight failed: MYAPI_EDITION must be full or lan')
  }
  const image = `${imageRepositoryForEdition(edition)}:${version}`
  const targetValues = { ...values, MYAPI_IMAGE: image }
  normalizeLANRuntimeValues(targetValues)
  const errors = validateRuntimeConfiguration(targetValues)
  if (errors.length > 0) {
    throw new Error(`upgrade preflight failed: ${errors.join('; ')}`)
  }
  return {
    paths,
    version,
    originalContents,
    values,
    targetValues,
    edition,
    image,
    currentImage: deploymentImage(values),
    verifySignature: shouldVerifyImageSignature(args, values),
    pinDigest: shouldPinImageDigest(args, values),
  }
}

function printUpgradeDryRun(plan, args) {
  const result = {
    mode: 'dry-run',
    projectDir: plan.paths.projectRoot,
    edition: plan.edition,
    currentImage: plan.currentImage,
    targetImage: plan.image,
    version: plan.version,
    // Upgrade always resolves the target to a versioned GHCR image. Local
    // builds remain available through `myapi build`, but must not silently
    // change the source of a release upgrade.
    imageSource: 'ghcr-pull',
    signatureVerification: plan.verifySignature ? 'requested-not-executed' : 'not-requested',
    imagePinning: plan.pinDigest ? 'requested-not-executed' : 'not-requested',
    imageResolution: plan.pinDigest ? 'digest-after-pull' : 'tag',
    checks: ['deployment-files', 'environment', 'runtime-configuration'],
    writes: [],
    dockerOperations: [],
  }
  if (args.includes('--json')) {
    console.log(JSON.stringify(result, null, 2))
    return
  }
  console.log('MyAPI upgrade dry-run: no files, containers, images, or data were changed.')
  console.log(`Project: ${result.projectDir}`)
  console.log(`Edition: ${result.edition}`)
  console.log(`Current image: ${result.currentImage}`)
  console.log(`Target image: ${result.targetImage}`)
  console.log('Image action: pull the pinned target image from GHCR')
  console.log(
    `Signature verification: ${result.signatureVerification === 'requested-not-executed' ? 'requested (not executed in dry-run)' : 'not requested'}`
  )
  console.log(`Digest pinning: ${result.imagePinning === 'requested-not-executed' ? 'requested (resolved after pull)' : 'not requested'}`)
  console.log('Preflight: deployment files, environment, and runtime configuration passed.')
  console.log('Next step: run the same command without --dry-run only on an approved copy.')
}

function upgradeDeployment(args) {
  const plan = buildUpgradePlan(args)
  const {
    paths,
    originalContents,
    values,
    image,
  } = plan
  if (plan.verifySignature && !plan.pinDigest) verifyImageSignature(image, values)
  const backupDir = path.join(paths.projectRoot, 'backups')
  const backupPath = path.join(
    backupDir,
    `myapi-upgrade-${new Date().toISOString().replace(/[:.]/g, '-')}.env`
  )
  mkdirSync(backupDir, { recursive: true, mode: 0o700 })
  writeFileSync(backupPath, originalContents, { mode: 0o600 })
  chmodSync(backupPath, 0o600)

  try {
    const updatedContents = setEnvValue(originalContents, 'MYAPI_IMAGE', image)
    writeFileSync(paths.envFile, updatedContents, { mode: 0o600 })
    chmodSync(paths.envFile, 0o600)
    let deployedImage = image
    let updatedValues = plan.targetValues
    run('docker', composeArguments(paths, ['pull', 'my-api']), {
      cwd: paths.projectRoot,
      env: composeEnvironment(updatedValues),
    })
    if (plan.pinDigest) {
      deployedImage = resolveImageDigest(image)
      if (plan.verifySignature) verifyImageSignature(deployedImage, values)
      const pinnedContents = setEnvValue(updatedContents, 'MYAPI_IMAGE', deployedImage)
      writeFileSync(paths.envFile, pinnedContents, { mode: 0o600 })
      chmodSync(paths.envFile, 0o600)
    }
    updatedValues = { ...plan.targetValues, MYAPI_IMAGE: deployedImage }
    run('docker', composeArguments(paths, ['up', '-d', '--force-recreate', '--wait', '--wait-timeout', '120']), {
      cwd: paths.projectRoot,
      env: composeEnvironment(updatedValues),
    })
    console.log(`MyAPI upgraded to ${deployedImage}. Environment backup: ${backupPath}`)
  } catch (error) {
    writeFileSync(paths.envFile, originalContents, { mode: 0o600 })
    chmodSync(paths.envFile, 0o600)
    let rollbackError
    try {
      const restoredValues = parseEnvFile(paths.envFile)
      run('docker', composeArguments(paths, ['up', '-d', '--force-recreate', '--wait', '--wait-timeout', '120']), {
        cwd: paths.projectRoot,
        env: composeEnvironment(restoredValues),
      })
    } catch (rollbackFailure) {
      rollbackError = rollbackFailure
    }
    const message = error instanceof Error ? error.message : String(error)
    if (rollbackError) {
      throw new Error(`${message}; automatic rollback failed: ${rollbackError.message}`)
    }
    throw new Error(`${message}; previous image restored and health-checked`)
  }
}

function printVersion(args) {
  const value = {
    package: packageMetadata.name,
    version: packageMetadata.version,
    distribution: 'MyAPI',
    machineSlug: 'my-api',
    // Keep a stable `upstream` field for scripts consuming older CLI JSON;
    // its value is intentionally branded as MyAPI rather than exposing a
    // legacy project name in user-facing output.
    upstream: 'MyAPI rc.25 distribution',
    repository: packageMetadata.repository.url,
  }
  if (args.includes('--json')) console.log(JSON.stringify(value))
  else console.log(`${value.package} ${value.version} (${value.upstream})`)
}

function printHelp() {
  console.log(`MyAPI self-hosting CLI

Usage:
  myapi init [directory]
  myapi configure [--project-dir DIR] [--public-url URL] [--data-dir DIR] [--logs-dir DIR]
  myapi migrate [--project-dir DIR]
  myapi doctor [--project-dir DIR]
  myapi upgrade --version VERSION [--project-dir DIR] [--verify-signature] [--pin-digest] [--dry-run] [--json]
  myapi adopt --project-dir DIR --data-dir DIR --logs-dir DIR
  myapi lan init [directory] [--bind-address ADDRESS] [--port PORT] [--allow-lan]
  myapi lan start|status|stop --project-dir DIR [--bind-address ADDRESS] [--port PORT] [--allow-lan]
  myapi build|up|down|status|logs [--project-dir DIR] [--follow]
  myapi version [--json]

The CLI never deploys during npm install, never removes Docker volumes, and
never prints SESSION_SECRET or API credentials. 'myapi up' pulls the pinned
MyAPI image from GHCR; set MYAPI_BUILD_LOCAL=true (or use a local/* image) to
build locally instead. Existing NEW_API_* deployment variables are read as
compatibility aliases; migrate writes MYAPI_* settings. Set MYAPI_EDITION=lan
for the private LAN edition (it keeps the host binding at 127.0.0.1 unless
MYAPI_BIND_ADDRESS is explicitly changed).`)
}

const [command = 'help', ...args] = process.argv.slice(2)

try {
  if (command === 'init') {
    validateArguments(args, { positional: 1 })
    initProject(args)
  } else if (command === 'configure') {
    validateArguments(args, {
      values: [
        '--project-dir',
        '--public-url',
        '--data-dir',
        '--logs-dir',
      ],
      flags: ['--force'],
    })
    configureProject(args)
  } else if (command === 'migrate') {
    validateArguments(args, { values: ['--project-dir'] })
    migrateDeploymentEnv(args)
  } else if (command === 'doctor') {
    validateArguments(args, { values: ['--project-dir'] })
    doctor(args)
  } else if (command === 'upgrade') {
    validateArguments(args, {
      values: ['--project-dir', '--version'],
      flags: ['--verify-signature', '--pin-digest', '--dry-run', '--json'],
    })
    if (args.includes('--json') && !args.includes('--dry-run')) {
      throw new Error('--json is only supported with --dry-run')
    }
    if (args.includes('--dry-run')) printUpgradeDryRun(buildUpgradePlan(args), args)
    else upgradeDeployment(args)
  } else if (command === 'adopt') {
    validateArguments(args, {
      values: ['--project-dir', '--data-dir', '--logs-dir'],
    })
    adoptDataPaths(args)
  } else if (command === 'lan') {
    const [lanSubcommand = 'help', ...lanArgs] = args
    if (lanSubcommand === 'help' || lanSubcommand === '--help' || lanSubcommand === '-h') {
      printHelp()
    } else {
      if (!['init', 'start', 'status', 'stop'].includes(lanSubcommand)) {
        throw new Error('LAN command must be init, start, status, or stop')
      }
      validateArguments(lanArgs, {
        positional: lanSubcommand === 'init' ? 1 : 0,
        values: ['--project-dir', '--bind-address', '--port'],
        flags: ['--allow-lan'],
      })
      lanCommand(lanSubcommand, lanArgs)
    }
  } else if (['build', 'up', 'down', 'status', 'logs'].includes(command)) {
    validateArguments(args, {
      values: ['--project-dir'],
      flags: command === 'logs' ? ['--follow'] : [],
    })
    deploymentCommand(command, args)
  } else if (command === 'version' || command === '--version' || command === '-v') {
    validateArguments(args, { flags: ['--json'] })
    printVersion(args)
  } else if (command === 'help' || command === '--help' || command === '-h') {
    printHelp()
  } else {
    fail(`unknown command "${command}"`)
    printHelp()
  }
} catch (error) {
  fail(error instanceof Error ? error.message : String(error))
}
